### ISSUE TITLE
Travel.js

### ISSUE THREAD

**Issue by KrowtennetworK** [AlexJezior/TheFallenImmortals#1]
I can't find the travel javascript anywhere in the files, this is all i need.  I REALLY want to work on your project!  Please contact me Krowten#0462 on discord

**Comment by AlexJezior** [comment]
Apologies for the late response on this. This code base sat on many different hard drives over the course of a couple years. There's a chance things went missing over that time, but the majority of it is there. As for missing, or incomplete, files, I don't have any way to resurrect these files. Best of luck.
